/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uno;
 
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author RArora
 */
public class PickColourFrame extends javax.swing.JFrame 
{
    private UnoCard.Colour wildColour = null;
    Boolean allow = false;
    PopUp popUp;
    
    public PickColourFrame() 
    {
        initComponents();
    }
    
    public PickColourFrame(PopUp pop) {
        initComponents();
        popUp = pop;
    }
    
    public UnoCard.Colour choseColour(UnoCard card) {
        if (card.getColour() == UnoCard.Colour.Wild){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(100,150,600,700);
        }
        return card.getColour();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 24)); // NOI18N
        jLabel1.setText("Pick the Colour of Your Wild Card !!");

        redButton.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        redButton.setText("RED");
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        blueButton.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        blueButton.setText("BLUE");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        yellowButton.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        yellowButton.setText("YELLOW");
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });

        greenButton.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        greenButton.setText("GREEN");
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        wildColour = UnoCard.Colour.Red;
        JLabel message = new JLabel("The Wild Card Colour is Red!!");
        message.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColour = UnoCard.Colour.Red;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        /*popUp.topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/small/" + popUp.game.getTopCardImage())));*/
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Finder\\images\\PNGs\\small\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColour(UnoCard.Colour.Red);
        popUp.dispose();
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        wildColour = UnoCard.Colour.Blue;
        JLabel message = new JLabel("The Wild Card Colour is Blue!!");
        message.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColour = UnoCard.Colour.Blue;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        /*popUp.topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/small/" + popUp.game.getTopCardImage())));*/
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Finder\\images\\PNGs\\small\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColour(UnoCard.Colour.Blue);
        popUp.dispose();
    }//GEN-LAST:event_blueButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        wildColour = UnoCard.Colour.Green;
        JLabel message = new JLabel("The Wild Card Colour is Green!!");
        message.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColour = UnoCard.Colour.Green;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        /*popUp.topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/small/" + popUp.game.getTopCardImage())));*/
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Finder\\images\\PNGs\\small\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColour(UnoCard.Colour.Green);
        popUp.dispose();
    }//GEN-LAST:event_greenButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        wildColour = UnoCard.Colour.Yellow;
        JLabel message = new JLabel("The Wild Card Colour is Yellow!!");
        message.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null, message);
        allow = true;
        this.dispose();
        popUp.declaredColour = UnoCard.Colour.Yellow;
        popUp.gameStage.setPidName(popUp.game.getCurrentPlayer());
        popUp.gameStage.setButtonIcons();
        /*popUp.topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/small/" + popUp.game.getTopCardImage())));*/
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Finder\\images\\PNGs\\small\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColour(UnoCard.Colour.Yellow);
        popUp.dispose();
    }//GEN-LAST:event_yellowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColourFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColourFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
